HSF/documents

- HSF-TN/draft-2016-PROJ/draft-HSF-TN-2016-PROJ.md
To provide further info for readers of the document, I've gone through and added links to websites for the mentioned tools like CMake etc. Generally, only the first mentions or important context are linked - though I can go through and link every mention if required.
I've also added a couple of extra points to sections:
- Note usefulness of testing for triaging/fixing bugs
- Note that release info should describe how versioning scheme relates to changes to API and/or ABI
- Hint that number of runtime environment variables should be limited
There are also a few very minor grammar updates.
> Link to listed tools, update testing/settings

- HSF-TN/draft-2016-PROJ/draft-HSF-TN-2016-PROJ.md
As requested in old PR -  I had to fiddle to get things displaying correctly on Github, but am not sure the text is formatted correctly for the pandoc template.
> Add new author/institute

- CWP/papers/roadmap/authors/address.txt
- CWP/papers/roadmap/authors/authors.txt
- CWP/papers/roadmap/authors/footnotes.txt
- CWP/papers/roadmap/latex/authors.tex
Something weird happened with @eduardo-rodrigues last PR that made the txt files not
be properly in utf-8. Fixed now with this PR.
Resulting authors.tex file copied to LaTeX area for roadmap.
All cosmetic fixes also made in upstream Google Doc.
> Fix encoding problem and small authorship corrections

- CWP/papers/roadmap/authors/address.txt
- CWP/papers/roadmap/authors/authors.txt
> Authors: add A. Sanchez

- CWP/papers/2017-11/README.md
- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp.tex
- CWP/papers/roadmap/README.md
Add some README files to some of the CWP directories with
old PDFs to explain their purpose.
Correct an unfortunate typo on the first real page of the Roadmap document.
> Minor revisions

- CWP/papers/HSF-CWP-2017-01_roadmap/authors/authors.txt
Only one new signer after the GDB in the end...
> Add new author

- CWP/papers/HSF-CWP-2017-01_roadmap/authors/address.txt
- CWP/papers/HSF-CWP-2017-01_roadmap/authors/authors.txt
- CWP/papers/HSF-CWP-2017-01_roadmap/latex/authors.tex
FYI, James Frost communicated with me privately
> Add new authors, regenerate latex for paper

- CWP/papers/HSF-CWP-2017-01_roadmap/authors/authors.txt
Apologies for not making a PR via a personal fork, which I know is the right way of doing it. I got some strange things in the history of the commits while trying that approach and am lacking of time to investigate right now. I just wanted to update the list of signatories with the latest names we received.
> Addition of extra signatories to the CWP

- CWP/papers/HSF-CWP-2017-01_roadmap/authors/address.txt
- CWP/papers/HSF-CWP-2017-01_roadmap/authors/authors.txt
I added the new authorship request from this week and fixed a duplication with UChicago and CHICAGO.
> CWP: fixed duplication of institute. Added a new signatory.

- .gitignore
- CWP/papers/HSF-CWP-2017-01_roadmap/authors/address.txt
- CWP/papers/HSF-CWP-2017-01_roadmap/authors/authors.txt
> Miscellaneous fixes to CWP author list

- CWP/papers/HSF-CWP-2017-01_roadmap/authors/address.txt
- CWP/papers/HSF-CWP-2017-01_roadmap/authors/authors.txt
This PR should fix https://github.com/HEP-SF/documents/issues/48.
I also caught a duplication of addresses, and fixed it.
> CWP authors list - updates and fixes

- CWP/papers/HSF-CWP-2017-01_roadmap/authors/authors.txt
* Request to sign sent by mail on March 12
> CWP authors: Add Andreas Heiss (KIT)

- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp.bib
Two small fixes to the CWP bibtex file.
> Remove duplicate bibtex entry and spurious comment

- CWP/papers/HSF-CWP-2017-04_doma/latex/hsf-cwp-dm.tex
- Changes made to Overleaf imported
- LaTeX cleanup
> CWP DOMA paper fixes

- CWP/papers/HSF-CWP-2017-01_roadmap/authors/address.txt
- CWP/papers/HSF-CWP-2017-01_roadmap/authors/authors.txt
- F. Derue added
- LPNHE affiliation citation updated to reflect change starting 2018-01-01
> Cwp signers update

- CWP/papers/HSF-CWP-2017-01_roadmap/authors/a2tex.py
Follow the style guide here:
https://jhep.sissa.it/jhep/help/JHEP/TeXclass/DOCS/JHEP-author-manual.pdf
> Correct JHEP author stype formatting

- CWP/papers/HSF-CWP-2017-01_roadmap/authors/a2tex.py
- CWP/papers/HSF-CWP-2017-01_roadmap/authors/authors.txt
- CWP/papers/HSF-CWP-2017-01_roadmap/authors/footnotes.txt
- CWP/papers/HSF-CWP-2017-01_roadmap/latex/authors.tex
- CWP/papers/HSF-CWP-2017-04_doma/authors/authors.txt
- CWP/papers/HSF-CWP-2017-04_doma/latex/authors.tex
> a2tex: add footnotes in author list (JHEP style) + improvements/fixes

- CWP/papers/HSF-CWP-2017-04_doma/latex/hsf-cwp-dm.tex
- Changes made up to 13/4 included
> CWP DOMA: import fixes from Overleaf

- CWP/papers/HSF-CWP-2017-01_roadmap/authors/address.txt
- CWP/papers/HSF-CWP-2017-01_roadmap/authors/authors.txt
- CWP/papers/HSF-CWP-2017-01_roadmap/latex/authors.tex
Address taken from recent CMS publication, but not yet sure if the University should be mentioned or not (I have asked Giuseppe).
> Add Andronico as author

- CWP/papers/HSF-CWP-2017-02_training/latex/cwp-wg-training-careers.tex
These are the changes to the document from @harveyj1953 and me. We don't consider this final yet, but it should be a significant step forwards and it's good for review by Dario and Sudir.
> Training john graeme edits

- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp.bib
- CWP/papers/HSF-CWP-2017-02_training/latex/cwp-wg-training-careers.tex
Changes from @menasce, rebased to the current HEAD with merge conflicts resolved.
New references added to master bibliography file
Citations properly done in text 
Many small corrections to spelling and grammar
> Proper citations for Training Paper

- CWP/papers/HSF-CWP-2017-02_training/latex/cwp-wg-training-careers.tex
> Missed middle initial

- CWP/papers/HSF-CWP-2017-08_framework/latex/df_fwk_summary.tex
I added and abstract to the frameworks paper that hopefully should get it into arXiv.
I corrected some small mistakes in the text as well.
There are definitely still issues with the references that need to be fixed before submission (and the final author list settled).
> Add frameworks paper abstract

- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp-main.tex
- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp.bib
Comments attributed to MJ in https://docs.google.com/document/d/1y1xrJxPkJcGxpuF_7NrCfCqLiy4b4Ahg2zZoQ9SWNCk/edit
> Address some reviewer comments

- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp-main.tex
- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp.bib
This is my latest set of edits for CSBS changes.
- Fixed some reference syntax issues with #113, #111 (maybe bad rebase?)
- Added additional citations for SLOC (from ALICE) and AArch64 power
- Added citation for FNAL accelerator schedule
I think from my TODO list that's everything...
> CSBS References and Fixes

- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp-main.tex
- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp.bib
answering the open issue for non-hep references (actually we had many of them in the bib already...)
> add references

- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp.bib
- split very long abstract line and fix double quote escaping
- fix missing }
Hopefully the last glitches...
> cwp.bib: miscellaneous fixes

- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp-main.tex
> CWP CSBS: fix comment related to AARC project participants

- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp-main.tex
Originally on @davidlange6 but I thought I could help...
> CWP CSBS: address comments about algorithms in 3.3

- .gitignore
- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp-csbs.tex
- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp-main.tex
- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp.bib
Fixed a few formatting issues that I found. Apologies that my editor (Atom) likes to aggressively tidy up whitespace (it's good, but leads to many trivial changes).
I found a better reference for Scikit-Learn too.
> Small fixes to references and LaTeX formatting

- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp.bib
- CWP/papers/HSF-CWP-2017-04_doma/latex/.gitignore
- CWP/papers/HSF-CWP-2017-04_doma/latex/hsf-cwp-dm.tex
This version taken from overleaf, with some references added by Bo and Michel
Add one reference to global cwp.bib file
Add a gitignore for the PDF output
> Update LaTeX adding references for DOMA paper

- CWP/papers/HSF-CWP-2017-01_roadmap/latex/cwp.bib
- CWP/papers/HSF-CWP-2017-08_framework/latex/df_fwk_summary.tex
Updated reference and author list for the framework document
> frameworks: author update and ALFA reference

- HSF-DOC/2018-01/README.md
Just adding an introductory README for HSF-DOC-2018-01.
> Added README file to HSF-DOC-2018-01

- LHCC/2020/2020-01/ctcs.bib
- LHCC/2020/2020-01/input_simulation.tex
> Update reference for GeantV adding recent paper on arXiv

- HSF-TN/draft-2016-PROJ/draft-HSF-TN-2016-PROJ.md
- English improvements
- Continuous integration
- Change license suggestions
> Review and update of Project Guidelines

- LHCC/2020/2020-01/authors.txt
> Fix Savannah's affiliation

- LHCC/2020/2020-01/Makefile
- LHCC/2020/2020-01/README.md
- LHCC/2020/2020-01/a2tex.py
- LHCC/2020/2020-01/address.txt
- LHCC/2020/2020-01/authors.txt
- LHCC/2020/2020-01/ctcs.tex
- LHCC/2020/2020-01/input_generators.tex
Update with a few fixes and new authors for the LHCC document
> Author fixes

- LHCC/2020/2020-01/README.md
- LHCC/2020/2020-01/authors.txt
Small updates to author list and infrastructure
> Lhcc fixes 2

- LHCC/2020/2020-01/ctcs.tex
Much more complete author list now
> Update DOI for CTCS Snowmass

- HSF-DOC/2022-01/.gitignore
- HSF-DOC/2022-01/hsf-history-paper.tex
- HSF-DOC/2022-01/jheppub.sty
- HSF-DOC/2022-01/refs.bib
> Add HSF History paper
